name: Integ-Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'msdIndu@99'  # Replace with actual password
          MYSQL_DATABASE: 'webapp'         # Replace with actual database name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: msdIndu@99  # Replace with actual password
        MYSQL_DATABASE: webapp 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Check MySQL Authentication
      run: mysql --host=${MYSQL_HOST} --port=${MYSQL_PORT} --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute='SHOW DATABASES;'
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: msdIndu@99        
    - name: Run Tests
      run: npm test
