name: CI/CD Workflow

on:
    pull_request:
      branches:
        - main

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: "latest"

    - name: Zip Repository
      run: |
        zip -r webapp.zip . -x "*.git*"
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: webapp.zip
    
    - name: Packer init
      run: |
          packer init packer/packer.pkr.hcl
    
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: app
        path: artifacts
    
    - name: Validate Packer Template
      run: |
        packer validate packer/packer.pkr.hcl
    
    - name: Build AMI with Packer
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DEMO_ACCOUNT_ID: ${{secrets.DEMO_ACCOUNT_ID}}
        AWS_REGION: "us-east-1"  # Adjust as per your requirement
      run: |
        packer build packer.pkr.hcl
